Enhance REST API with Advanced Authentication and Endpoint Configuration
iklobato/LightAPI pull request #6
Opened 2024-09-08 23:00 UTC by iklobato

- Added `AbstractAuthentication` class for flexible authentication mechanisms.
- Implemented `DefaultJWTAuthentication` with dynamic SECRET_KEY generation.
- Updated `RestEndpoint` class to support custom authentication and configuration options.
- Added detailed docstrings and usage examples for `RestEndpoint`.
- Integrated advanced example of `RestEndpoint` configuration including custom authentication, HTTP method handling, and route exclusion.

These changes provide a more secure and flexible API framework, supporting advanced authentication and endpoint customization.

2024-09-08 23:07 UTC, iklobato commented
Hi @MyGodItsFull0fStars this is one idea of the person usage
```
from authentication import DefaultJWTAuthentication

class ProductEndpoint(RestEndpoint):
    http_verbs = ['get', 'post', 'patch']  # Enable GET, POST, and PATCH methods
    http_exclude = ['put', 'delete']       # Exclude PUT and DELETE methods
    authentication = DefaultJWTAuthentication
```

The person can provide a single endpoint that depends or not of a model, and then, overwrite its methods to create the HTTP verbs from it. So on this example it will create GET, POST and PATCH automatically, and not create PUT and DELETE
Im also adding natively a class JWT authentication that handles automatically auhtentication if provided, with no additional libraries.

The person can also crate its own authentication method like
```
class MyCustomAuth(AbstractAuthentication):
    ...
```
and just need to provide generate_token and authenticate method, so its be called from the rest endpoint itself

2024-09-09 18:57 UTC, MyGodItsFull0fStars commented
I skimmed the code changes and it looks very good so far! I will test it on my device tomorrow more thoroughly!

2024-09-09 19:00 UTC, iklobato commented
That's awesome! My goal in the near future is to support startups in building their prototypes using this framework. The idea is to help them create the same solutions with fewer development hours. Most people don't want to spend too much time on simple tasks, so by keeping things straightforward, even managers will be able to create what they need on their own.



Thanks for the support!


> On 9 Sep 2024, at 15:57, Christian Bauer ***@***.***> wrote:
> 
> 
> I skimmed the code changes and it looks very good so far! I will test it on my device tomorrow more thoroughly!
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/iklobato/LightAPI/pull/6#issuecomment-2338859175>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AEKLDKK3FNTWVGWEES7FRUDZVXVSDAVCNFSM6AAAAABN3MJFTCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMZYHA2TSMJXGU>.
> You are receiving this because you authored the thread.
>

2024-09-10 20:40 UTC, MyGodItsFull0fStars requested changes
Looks great to me! There were a few minor issues I have found, plus some suggestions, ideas and personal preferences.

Overall I really love the structure, it's clear, readable and easy to comprehend.

As said in one of the comments, if you prefer a broader Python support < 3.9 then I will change the _type hints_ in my commits to address this. 

I will mark the review as `Request changes` only because the imports should be sorted and grouped properly and the `configure` method of the `RestEndpoint` class likely needs a `@abstractmethod` decorator.

Have a nice day!
-Chris

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on examples/person_endpoint.py
> +    app.register(
Nice! Wanted to ask you if that variant would also be okay with you, as it actually uses the dictionary.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/auth.py
> +class AbstractAuthentication(ABC):
This abstraction will definitely help a lot o make sure the necessary things will be implemented without having to dig through the code too much.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/auth.py
> +class AbstractAuthentication(ABC):
One thing we probably should also include is the usage of a `.env` file for the `SECRET_KEY` so it will (hopefully) not be exposed to the outside world.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/auth.py
> +    ALGORITHM = "HS256"
Later on, if multiple algorithms are supported, we can create a `Enum` class for the supported variants.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/auth.py
> +    def decode_token(self, token: str) -> Union[Dict, None]:
This comment is more a question on my part. You here use the `typing` library for _type hints_, which is totally fine. I am just asking if you prefer to use this library instead of the built-in variants that are supported from Python 3.9 on? Which of course has a larger language support than the built-in ones.

Just asking which you want to continue using in this project, since mixing them is not a great idea imo and I gladly can update my changes to use the `typing` library instead of built-in type hints.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/auth.py
> +            # Handle expired token
Yet missing, but I guess for now thats surely okay :)

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/exceptions.py
> +            f"Missing implementation for {handler_name} required for HTTP verb: {verb}. "
Is the trailing `blank` character intentional? If not please remove.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/rest.py
> +    def configure(self) -> None:
As it is an abstract class, the `@abstractmethod` decorator makes sense to be more declarative.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/lightapi.py
> +from typing import Dict, Type, Callable
The imports should be grouped and sorted similar to:

```python
import logging
from typing import Callable, Dict, Type

from aiohttp import web
from sqlalchemy.exc import SQLAlchemyError

from lightapi.database import Base, engine
from lightapi.handlers import create_handler
from lightapi.rest import RestEndpoint
```

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/auth.py
> +    def authenticate(self, token: str) -> Type[NotImplementedError, Optional[Dict[str, str]]]:
As `Type[...]` expects only one parameter, you need to wrap the inner part of the brackets with `Union` like `Type[Union[NotImplementedError, Optional[Dict[str, str]]]]`.

Maybe a type alias could make the code more readable as there is a lot happening at once.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/rest.py
> +        'post', 'get', 'put', 'delete', 'patch', 'options', 'head'
IMO we should introduce a HTTP method constant class consisting of `StrEnum` or constant strings.
But that's my preference, as I am a sucker for enums and not reusing strings.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/auth.py
> +            'exp': datetime.datetime.utcnow() + self.EXPIRATION_DELTA
FYI the method `utcnow` is marked as deprecated in more recent Python versions.

2024-09-10 20:40 UTC, MyGodItsFull0fStars commented on lightapi/auth.py
> +from abc import ABC, abstractmethod
The order of imports is recommended as:

```python
import datetime
import os
from abc import ABC, abstractmethod
from typing import Dict, Optional, Type, Union

import jwt
from aiohttp import web

```

2024-09-11 01:27 UTC, iklobato-w commented on lightapi/auth.py
> +class AbstractAuthentication(ABC):
Totally!

2024-09-11 01:27 UTC, iklobato-w commented on lightapi/auth.py
> +    ALGORITHM = "HS256"
Agree!

2024-09-11 01:32 UTC, iklobato-w commented on lightapi/rest.py
> +        'post', 'get', 'put', 'delete', 'patch', 'options', 'head'
I think Enums will fit better here indeed

2024-09-13 00:50 UTC, merged

2024-09-13 21:17 UTC, MyGodItsFull0fStars reviewed
Awesome! Many of the changes you made resulted in leaner code, which is always nice!

I will be on vacation from tomorrow on, so while you can still assign PRs to me, I will only be available from 23th of September again, just to let you know!

2024-09-13 23:50 UTC, iklobato-w commented
Hah no problem! Have a good trip!

I dont know from where you are, but if you use WhatsApp you can add me there +55 11 9 8434 8555

See u!

On 13 Sep 2024, at 18:18, Christian Bauer ***@***.***> wrote:



@MyGodItsFull0fStars commented on this pull request.

Awesome! Many of the changes you made resulted in leaner code, which is always nice!

I will be on vacation from tomorrow on, so while you can still assign PRs to me, I will only be available from 23th of September again, just to let you know!

—
Reply to this email directly, view it on GitHub<https://github.com/iklobato/LightAPI/pull/6#pullrequestreview-2304175364>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BKA3RTYGTCBPTD3K6GHGD3LZWNJARAVCNFSM6AAAAABN3MJFTCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMBUGE3TKMZWGQ>.
You are receiving this because you commented.Message ID: ***@***.***>